// Dados dos produtos
const defaultProducts = [
  {
    id: '1',
    name: 'Natura Luna',
    description: 'Perfume feminino floral, notas de jasmim e sândalo. Uma fragrância delicada e sofisticada para momentos especiais.',
    price: 149.90,
    category: 'perfumes',
    brand: 'Natura',
    image: 'images/product-perfume-1.png',
    stock: 10,
    isAvailable: true,
  },
  {
    id: '2',
    name: 'Avon Far Away',
    description: 'Colônia feminina amadeirada com notas de baunilha e musk. Perfeita para o dia a dia.',
    price: 89.90,
    category: 'colonias',
    brand: 'Avon',
    image: 'images/product-perfume-2.png',
    stock: 15,
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Natura Ekos Creme',
    description: 'Hidratante corporal com óleo de castanha. Nutre profundamente a pele com ingredientes da biodiversidade brasileira.',
    price: 59.90,
    category: 'corpo',
    brand: 'Natura',
    image: 'images/product-body-1.png',
    stock: 20,
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Natura Tododia',
    description: 'Creme hidratante para mãos e corpo com aveia. Textura leve e absorção rápida.',
    price: 34.90,
    category: 'corpo',
    brand: 'Natura',
    image: 'images/product-body-2.png',
    stock: 25,
    isAvailable: true,
  },
  {
    id: '5',
    name: 'Natura Plant Shampoo',
    description: 'Shampoo fortalecedor com extratos naturais. Limpa suavemente e fortalece os fios.',
    price: 42.90,
    category: 'cabelo',
    brand: 'Natura',
    image: 'images/product-hair-1.png',
    stock: 12,
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Avon Advance',
    description: 'Condicionador reparador para cabelos danificados. Repara pontas duplas e dá brilho.',
    price: 38.90,
    category: 'cabelo',
    brand: 'Avon',
    image: 'images/product-hair-2.png',
    stock: 8,
    isAvailable: true,
  },
  {
    id: '7',
    name: 'Natura Una Batom',
    description: 'Batom matte de longa duração. Cor intensa e hidratação por até 8 horas.',
    price: 49.90,
    category: 'maquiagem',
    brand: 'Natura',
    image: 'images/product-makeup-1.png',
    stock: 30,
    isAvailable: true,
  },
  {
    id: '8',
    name: 'Avon True Color',
    description: 'Paleta de sombras com 8 cores vibrantes. Alta pigmentação e durabilidade.',
    price: 69.90,
    category: 'maquiagem',
    brand: 'Avon',
    image: 'images/product-makeup-2.png',
    stock: 5,
    isAvailable: true,
  },
];

// Categorias
const categories = {
  all: 'Todos',
  perfumes: 'Perfumes',
  colonias: 'Colônias',
  cabelo: 'Cabelo',
  corpo: 'Corpo',
  maquiagem: 'Maquiagem',
  skincare: 'Skincare',
};

// Configurações
const CONFIG = {
  deliveryFee: 15,
  freeDeliveryThreshold: 200,
  whatsappNumber: '5592984663068',
  adminUser: 'AnaSantos',
  adminPass: 'Asantos1969',
  backendBaseUrl: '',
};
